In [1]:
import numpy as np

In [99]:
X = np.array([1,5.6]).reshape(2,1)
X

array([[1. ],
       [5.6]])

In [100]:
Y = np.array([60]).reshape(1,1)
Y.shape

(1, 1)

In [85]:
#initializing weights
np.random.seed(0)
def weight_initializer(shape0,shape1):
    return np.random.randn(shape0,shape1)*0.1

In [86]:
#bias initialize
def bias_initializer(shape0,shape1):
    return np.zeros((shape0,shape1))

In [87]:
#linear step
def linear_(W,X,b):
    return np.dot(W.T,X) + b

In [88]:
#sigmoid activation function
def activation(z):
    return 1/(1+np.exp(-z))

In [89]:
#binary crossentropy
def loss(Y,yhat):
    return -1* (np.dot(Y,np.log(yhat)) + np.dot((1-Y),np.log(1-yhat)))

In [90]:
#L1 (Input layer to 1st hidden layer) hidden layer with 4 neurons
W1 = weight_initializer(2,4)
b1 = bias_initializer(4,1)
z1 = linear_(W1,X,b1)
a1 = activation(z1)
print(W1)

[[ 0.17640523  0.04001572  0.0978738   0.22408932]
 [ 0.1867558  -0.09772779  0.09500884 -0.01513572]]


In [91]:
#L2 (1st hidden layer to output layer)
W2 = weight_initializer(4,1)
b2 = bias_initializer(1,1)
z2 = linear_(W2,a1,b2)
a2 = activation(z2)
print(W2) #predicted value

[[-0.01032189]
 [ 0.04105985]
 [ 0.01440436]
 [ 0.14542735]]


In [71]:
loss(Y,a2)

array([[-19.18887337]])

In [96]:
def initialize_parameter(X,L):
    np.random.seed(0)
    L.insert(0,X.shape[0])
    parameters = {}
    for i in range(1,len(L)-1):
        parameters['W'+str(i)] = np.random.randn(L[i],L[i-1])*0.1
        parameters['b'+str(i)] = np.zeros((L[i],1))   
        
    return parameters

In [97]:
L = [4,3,1]

In [98]:
initialize_parameter(X,L)

{'W1': array([[ 0.17640523,  0.04001572],
        [ 0.0978738 ,  0.22408932],
        [ 0.1867558 , -0.09772779],
        [ 0.09500884, -0.01513572]]),
 'b1': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'W2': array([[-0.01032189,  0.04105985,  0.01440436,  0.14542735],
        [ 0.07610377,  0.0121675 ,  0.04438632,  0.03336743],
        [ 0.14940791, -0.02051583,  0.03130677, -0.08540957]]),
 'b2': array([[0.],
        [0.],
        [0.]])}