In [1]:
import numpy as np

In [2]:
X = np.array([1,5.6]).reshape(2,1)
X

array([[1. ],
       [5.6]])

In [3]:
Y = np.array([60]).reshape(1,1)
Y.shape

(1, 1)

# Manual work 

In [4]:
#initializing weights

def weight_initializer(shape0,shape1):
    return np.random.randn(shape1,shape0)*0.1

In [5]:
#bias initialize
def bias_initializer(shape0,shape1):
    return np.zeros((shape0,shape1))

In [6]:
#linear step
def linear_(W,X,b):
    return np.dot(W,X) + b

In [7]:
#sigmoid activation function
def activation(z):
    return 1/(1+np.exp(-z))

In [8]:
#binary crossentropy
def loss(Y,yhat):
    return -1* (np.dot(Y,np.log(yhat)) + np.dot((1-Y),np.log(1-yhat)))

In [9]:
#L1 (Input layer to 1st hidden layer) hidden layer with 4 neurons
np.random.seed(0)
W1 = weight_initializer(2,4)
b1 = bias_initializer(4,1)
z1 = linear_(W1,X,b1)
a1 = activation(z1)
print(W1)
print(W1.shape)

[[ 0.17640523  0.04001572]
 [ 0.0978738   0.22408932]
 [ 0.1867558  -0.09772779]
 [ 0.09500884 -0.01513572]]
(4, 2)


In [10]:
#L2 (1st hidden layer to 2nd hidden layer)
W2 = weight_initializer(4,3)
b2 = bias_initializer(3,1)
z2 = linear_(W2,a1,b2)
a2 = activation(z2)
print(W2)
print(W2.shape)

[[-0.01032189  0.04105985  0.01440436  0.14542735]
 [ 0.07610377  0.0121675   0.04438632  0.03336743]
 [ 0.14940791 -0.02051583  0.03130677 -0.08540957]]
(3, 4)


In [11]:
#L3 (2nd hidden layer to output layer)
W3 = weight_initializer(3,1)
b3 = bias_initializer(1,1)
z3 = linear_(W3,a2,b3)
a3 = activation(z3)
print(W3) #predicted value


[[-0.25529898  0.06536186  0.08644362]]


In [12]:
loss(Y,a3)

array([[4.02945371]])

# Dynamic work

In [13]:
def initialize_parameter(s0,L):
    np.random.seed(0)
    L.insert(0,s0)
    parameters = {}
    for i in range(1,len(L)):
        parameters['W'+str(i)] = np.random.randn(L[i],L[i-1])*0.1
        parameters['b'+str(i)] = np.zeros((L[i],1))   
    return parameters

In [14]:
L = [4,3,1]
parameters = initialize_parameter(X.shape[0],L)
parameters

{'W1': array([[ 0.17640523,  0.04001572],
        [ 0.0978738 ,  0.22408932],
        [ 0.1867558 , -0.09772779],
        [ 0.09500884, -0.01513572]]),
 'b1': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'W2': array([[-0.01032189,  0.04105985,  0.01440436,  0.14542735],
        [ 0.07610377,  0.0121675 ,  0.04438632,  0.03336743],
        [ 0.14940791, -0.02051583,  0.03130677, -0.08540957]]),
 'b2': array([[0.],
        [0.],
        [0.]]),
 'W3': array([[-0.25529898,  0.06536186,  0.08644362]]),
 'b3': array([[0.]])}

In [15]:
def forward_pass(X,Y,parameters):
    linear_pass_output = {}
    X = X
    a = len(parameters)//2
    for i in range(1,a+1):
        W = parameters["W" + str(i)]
        b = parameters["b" + str(i)] 
        z = np.dot(W,X) + b
        a = 1/(1+np.exp(-z))
        X = a
        linear_pass_output['z' + str(i)] = z
        linear_pass_output['a' + str(i)] = a
    l_f = loss(Y,X)
    return l_f,linear_pass_output

In [16]:
loss_val,_ = forward_pass(X,Y,parameters)

In [17]:
loss_val

array([[4.02945371]])